@extends('layouts.app')

@section('content')
<div class="space-y-8 print:space-y-4 print:text-black">

    <!-- Header Section (Hidden during print if custom styling, but standard print hides layout header) -->
    <div class="flex flex-col md:flex-row md:items-center md:justify-between space-y-4 md:space-y-0 print:hidden">
        <div>
            <h1 class="text-3xl font-extrabold tracking-tight text-white sm:text-4xl">Intelligence Reports</h1>
            <p class="text-sm text-slate-400 mt-1">Export summaries, rankings, and diagnostics worksheets</p>
        </div>
        <div>
            <button onclick="window.print()" class="px-5 py-2.5 rounded-xl bg-gradient-to-r from-orange-500 to-amber-500 hover:opacity-95 text-slate-950 font-bold text-sm tracking-wide transition flex items-center space-x-2 shadow-lg cursor-pointer">
                <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"/>
                </svg>
                <span>Print Report</span>
            </button>
        </div>
    </div>

    <!-- Print Header (Only visible on print) -->
    <div class="hidden print:block border-b-2 border-slate-900 pb-4 mb-6">
        <h1 class="text-3xl font-black uppercase text-slate-950 tracking-tight">WIDYACTIVE ATHLETE SYSTEM</h1>
        <p class="text-xs text-slate-600 tracking-wide uppercase font-bold mt-1">Daily Intelligence & Performance Report Summary</p>
        <div class="flex justify-between text-xs text-slate-500 mt-4">
            <span>Date: {{ date('F d, Y') }}</span>
            <span>Generated by: {{ Auth::user()->name ?? 'Coach Portal' }}</span>
        </div>
    </div>

    <!-- Stats Summary Panel -->
    <div class="grid grid-cols-3 gap-5 print:border print:border-slate-300 print:rounded-lg print:p-4 print:mb-6">
        <div class="glass-card p-5 border border-white/5 bg-slate-900/40 text-center print:border-none print:bg-transparent">
            <span class="block text-xs font-bold text-slate-400 uppercase tracking-widest print:text-slate-600">Active Squad</span>
            <span class="block text-3xl font-extrabold text-white mt-1 print:text-black">{{ $totalAthletes }} athletes</span>
        </div>
        <div class="glass-card p-5 border border-white/5 bg-slate-900/40 text-center print:border-none print:bg-transparent">
            <span class="block text-xs font-bold text-slate-400 uppercase tracking-widest print:text-slate-600">Avg Performance</span>
            <span class="block text-3xl font-extrabold text-white mt-1 print:text-black">{{ $avgPerformance }}%</span>
        </div>
        <div class="glass-card p-5 border border-white/5 bg-slate-900/40 text-center print:border-none print:bg-transparent">
            <span class="block text-xs font-bold text-slate-400 uppercase tracking-widest print:text-slate-600">Avg Readiness</span>
            <span class="block text-3xl font-extrabold text-white mt-1 print:text-black">{{ $avgReadiness }}%</span>
        </div>
    </div>

    <!-- Complete Directory Worksheet -->
    <div class="glass-card border border-white/5 overflow-hidden print:border print:border-slate-300 print:rounded-lg">
        <div class="px-6 py-4 bg-slate-950/60 border-b border-white/5 print:bg-slate-100 print:border-slate-300">
            <h3 class="text-base font-bold text-white print:text-slate-950">Squad Diagnostic Assessment Worksheet</h3>
        </div>
        
        <div class="overflow-x-auto">
            <table class="min-w-full divide-y divide-white/5 text-left text-xs text-slate-300 print:divide-slate-300 print:text-slate-900">
                <thead class="bg-slate-950/20 text-slate-400 font-bold uppercase tracking-wider print:text-slate-700 print:bg-slate-50">
                    <tr>
                        <th class="px-6 py-3">Athlete</th>
                        <th class="px-6 py-3">Sport</th>
                        <th class="px-6 py-3 text-center">Avg Performance</th>
                        <th class="px-6 py-3 text-center">Avg Readiness</th>
                        <th class="px-6 py-3 text-center">Attendance</th>
                        <th class="px-6 py-3 text-right">Intel Prediction</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-white/5 print:divide-slate-200">
                    @forelse($athletes as $athlete)
                        <tr class="hover:bg-white/[0.01] print:bg-transparent">
                            <td class="px-6 py-4 font-bold text-white print:text-slate-950">{{ $athlete->name }}</td>
                            <td class="px-6 py-4 font-medium">{{ ucfirst($athlete->sport) }}</td>
                            <td class="px-6 py-4 text-center font-black text-amber-400 print:text-slate-900">{{ $athlete->average_performance }}%</td>
                            <td class="px-6 py-4 text-center font-black text-orange-400 print:text-slate-900">{{ $athlete->average_readiness }}%</td>
                            <td class="px-6 py-4 text-center font-bold text-emerald-400 print:text-slate-900">{{ $athlete->attendance_rate }}%</td>
                            <td class="px-6 py-4 text-right font-bold uppercase tracking-wide
                                @if($athlete->prediction === 'Elite Candidate')
                                    text-yellow-400 print:text-slate-900
                                @elseif($athlete->prediction === 'Consistent Performer')
                                    text-orange-400 print:text-slate-900
                                @elseif($athlete->prediction === 'Needs Focus')
                                    text-red-400 print:text-slate-900
                                @else
                                    text-slate-400 print:text-slate-600
                                @endif">
                                {{ $athlete->prediction }}
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="6" class="px-6 py-10 text-center text-slate-500">No athletes registered.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

</div>

<!-- Print-specific Styles -->
<style>
    @media print {
        header, footer, nav, button, .print\:hidden {
            display: none !important;
        }
        body {
            background: white !important;
            color: black !important;
            font-size: 12pt !important;
        }
        .glass-card {
            border: none !important;
            background: transparent !important;
            box-shadow: none !important;
            backdrop-filter: none !important;
            padding: 0 !important;
        }
    }
</style>
@endsection
